Repository CA-G12/Quiz-App-TeamOne, pull requests merged in 2022-07, with the labels that each got.

#3 2 construct file structure
  CSS/quiz.css
  CSS/style.css
  Html/quiz.html
  index.html
  javascript/main.js
  javascript/quiz.js
Labels: waiting Review

#7 4 write quiz.html file
  Html/quiz.html
  assert/logoicon.png
Labels: awaiting review

#8 writing user stories and user journey
  README.md
Labels: approved

#9 Riyad branch
  CSS/quiz.css
  CSS/style.css
  img/Logo.png
  index.html
Labels: awaiting review

#11 Finishing the readme.md file.
  README.md
Labels: approved

#12 6 styling quiz page
  CSS/quiz.css
  Html/quiz.html
Labels: awaiting review

#14 javascript/main.js is Finished
  index.html
  javascript/main.js
Labels: approved

#16 adding dashboard.html file
  Html/dashboard.html
Labels: awaiting review

#17 15 creating and writing result page
  CSS/dashboard.css
  Html/dashboard.html
  Html/quiz.html
Labels: approved

#21 Added the javascript functionality to the quiz page.
  Html/quiz.html
  javascript/quiz.js
Labels: awaiting review

#22 fixed linking to logo
  Html/dashboard.html
  Html/quiz.html
Labels: bug, awaiting review

#20 10 create js for the landingpage
  CSS/style.css
  index.html
  javascript/main.js
Labels: awaiting review

#23 15 creating and writing result page
  Html/dashboard.html
  javascript/dashborad.js
Labels: awaiting review

#26 Show the result functionlaity
  javascript/quiz.js
Labels: awaiting review

#27 relates #25
  javascript/dashborad.js
  javascript/quiz.js
Labels: awaiting review

#28 Added the fork live link to the readme file
  README.md
Labels: done

#30 Modified the live link to the original one
  README.md
Labels: awaiting review
